name: Daily CSV Export via Playwright Docker

on:
  schedule:
    - cron: '0 1 * * *' # 08:00 WIB setiap hari
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy
      options: --ipc=host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run export script
        run: node scripts/export-inaproc.js

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: inaproc_csv
          path: downloads/inaproc_2024.csv
